ALTER TABLE columns ADD COLUMN color VARCHAR(7) NOT NULL DEFAULT '#6B7280';
ALTER TABLE columns ADD COLUMN wip_limit INTEGER;
ALTER TABLE tasks ADD COLUMN priority VARCHAR(20) NOT NULL DEFAULT 'medium';
