// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: boards.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (tenant_id, project_id, name)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, project_id, name, created_at, updated_at
`

type CreateBoardParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, createBoard, arg.TenantID, arg.ProjectID, arg.Name)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBoard = `-- name: DeleteBoard :exec
DELETE FROM boards WHERE id = $1 AND tenant_id = $2
`

type DeleteBoardParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteBoard(ctx context.Context, arg DeleteBoardParams) error {
	_, err := q.db.Exec(ctx, deleteBoard, arg.ID, arg.TenantID)
	return err
}

const getBoardByID = `-- name: GetBoardByID :one
SELECT id, tenant_id, project_id, name, created_at, updated_at FROM boards WHERE id = $1 AND tenant_id = $2
`

type GetBoardByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetBoardByID(ctx context.Context, arg GetBoardByIDParams) (Board, error) {
	row := q.db.QueryRow(ctx, getBoardByID, arg.ID, arg.TenantID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBoardsByProjectID = `-- name: GetBoardsByProjectID :many
SELECT id, tenant_id, project_id, name, created_at, updated_at FROM boards WHERE project_id = $1 AND tenant_id = $2 ORDER BY created_at
`

type GetBoardsByProjectIDParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetBoardsByProjectID(ctx context.Context, arg GetBoardsByProjectIDParams) ([]Board, error) {
	rows, err := q.db.Query(ctx, getBoardsByProjectID, arg.ProjectID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Board{}
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE boards
SET name = COALESCE($1, name),
    updated_at = NOW()
WHERE id = $2 AND tenant_id = $3
RETURNING id, tenant_id, project_id, name, created_at, updated_at
`

type UpdateBoardParams struct {
	Name     pgtype.Text `json:"name"`
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, updateBoard, arg.Name, arg.ID, arg.TenantID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
