// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: columns.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createColumn = `-- name: CreateColumn :one
INSERT INTO columns (tenant_id, board_id, name, position, color, wip_limit)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, board_id, name, position, created_at, updated_at, color, wip_limit
`

type CreateColumnParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	BoardID  pgtype.UUID `json:"board_id"`
	Name     string      `json:"name"`
	Position int32       `json:"position"`
	Color    string      `json:"color"`
	WipLimit pgtype.Int4 `json:"wip_limit"`
}

func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (Column, error) {
	row := q.db.QueryRow(ctx, createColumn,
		arg.TenantID,
		arg.BoardID,
		arg.Name,
		arg.Position,
		arg.Color,
		arg.WipLimit,
	)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.WipLimit,
	)
	return i, err
}

const deleteColumn = `-- name: DeleteColumn :exec
DELETE FROM columns WHERE id = $1 AND tenant_id = $2
`

type DeleteColumnParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteColumn(ctx context.Context, arg DeleteColumnParams) error {
	_, err := q.db.Exec(ctx, deleteColumn, arg.ID, arg.TenantID)
	return err
}

const getColumnsByBoardID = `-- name: GetColumnsByBoardID :many
SELECT id, tenant_id, board_id, name, position, created_at, updated_at, color, wip_limit FROM columns WHERE board_id = $1 AND tenant_id = $2 ORDER BY position
`

type GetColumnsByBoardIDParams struct {
	BoardID  pgtype.UUID `json:"board_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetColumnsByBoardID(ctx context.Context, arg GetColumnsByBoardIDParams) ([]Column, error) {
	rows, err := q.db.Query(ctx, getColumnsByBoardID, arg.BoardID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Column{}
	for rows.Next() {
		var i Column
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BoardID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Color,
			&i.WipLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxColumnPosition = `-- name: GetMaxColumnPosition :one
SELECT COALESCE(MAX(position), -1)::int as max_position
FROM columns WHERE board_id = $1 AND tenant_id = $2
`

type GetMaxColumnPositionParams struct {
	BoardID  pgtype.UUID `json:"board_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetMaxColumnPosition(ctx context.Context, arg GetMaxColumnPositionParams) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxColumnPosition, arg.BoardID, arg.TenantID)
	var max_position int32
	err := row.Scan(&max_position)
	return max_position, err
}

const updateColumn = `-- name: UpdateColumn :one
UPDATE columns
SET name = COALESCE($1, name),
    color = COALESCE($2, color),
    wip_limit = COALESCE($3, wip_limit),
    updated_at = NOW()
WHERE id = $4 AND tenant_id = $5
RETURNING id, tenant_id, board_id, name, position, created_at, updated_at, color, wip_limit
`

type UpdateColumnParams struct {
	Name     pgtype.Text `json:"name"`
	Color    pgtype.Text `json:"color"`
	WipLimit pgtype.Int4 `json:"wip_limit"`
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateColumn(ctx context.Context, arg UpdateColumnParams) (Column, error) {
	row := q.db.QueryRow(ctx, updateColumn,
		arg.Name,
		arg.Color,
		arg.WipLimit,
		arg.ID,
		arg.TenantID,
	)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.WipLimit,
	)
	return i, err
}

const updateColumnPosition = `-- name: UpdateColumnPosition :exec
UPDATE columns SET position = $3, updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
`

type UpdateColumnPositionParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Position int32       `json:"position"`
}

func (q *Queries) UpdateColumnPosition(ctx context.Context, arg UpdateColumnPositionParams) error {
	_, err := q.db.Exec(ctx, updateColumnPosition, arg.ID, arg.TenantID, arg.Position)
	return err
}
