// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO task_comments (tenant_id, task_id, user_id, content)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, task_id, user_id, content, created_at, updated_at
`

type CreateCommentParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	TaskID   pgtype.UUID `json:"task_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Content  string      `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (TaskComment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.TenantID,
		arg.TaskID,
		arg.UserID,
		arg.Content,
	)
	var i TaskComment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TaskID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM task_comments WHERE id = $1 AND tenant_id = $2
`

type DeleteCommentParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.db.Exec(ctx, deleteComment, arg.ID, arg.TenantID)
	return err
}

const getCommentsByTaskID = `-- name: GetCommentsByTaskID :many
SELECT tc.id, tc.task_id, tc.user_id, tc.content, tc.created_at, tc.updated_at,
       u.display_name, u.avatar_url
FROM task_comments tc
JOIN users u ON u.id = tc.user_id
WHERE tc.task_id = $1 AND tc.tenant_id = $2
ORDER BY tc.created_at
`

type GetCommentsByTaskIDParams struct {
	TaskID   pgtype.UUID `json:"task_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type GetCommentsByTaskIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Content     string             `json:"content"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) GetCommentsByTaskID(ctx context.Context, arg GetCommentsByTaskIDParams) ([]GetCommentsByTaskIDRow, error) {
	rows, err := q.db.Query(ctx, getCommentsByTaskID, arg.TaskID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCommentsByTaskIDRow{}
	for rows.Next() {
		var i GetCommentsByTaskIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE task_comments SET content = $2, updated_at = NOW()
WHERE id = $1 AND tenant_id = $3
RETURNING id, tenant_id, task_id, user_id, content, created_at, updated_at
`

type UpdateCommentParams struct {
	ID       pgtype.UUID `json:"id"`
	Content  string      `json:"content"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (TaskComment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Content, arg.TenantID)
	var i TaskComment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TaskID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
