// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: labels.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTaskLabel = `-- name: AddTaskLabel :exec
INSERT INTO task_labels (task_id, label_id) VALUES ($1, $2)
`

type AddTaskLabelParams struct {
	TaskID  pgtype.UUID `json:"task_id"`
	LabelID pgtype.UUID `json:"label_id"`
}

func (q *Queries) AddTaskLabel(ctx context.Context, arg AddTaskLabelParams) error {
	_, err := q.db.Exec(ctx, addTaskLabel, arg.TaskID, arg.LabelID)
	return err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO labels (tenant_id, name, color)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name, color, created_at
`

type CreateLabelParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
	Color    string      `json:"color"`
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, createLabel, arg.TenantID, arg.Name, arg.Color)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLabel = `-- name: DeleteLabel :exec
DELETE FROM labels WHERE id = $1 AND tenant_id = $2
`

type DeleteLabelParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteLabel(ctx context.Context, arg DeleteLabelParams) error {
	_, err := q.db.Exec(ctx, deleteLabel, arg.ID, arg.TenantID)
	return err
}

const getLabelsByTenantID = `-- name: GetLabelsByTenantID :many
SELECT id, tenant_id, name, color, created_at FROM labels WHERE tenant_id = $1 ORDER BY name
`

func (q *Queries) GetLabelsByTenantID(ctx context.Context, tenantID pgtype.UUID) ([]Label, error) {
	rows, err := q.db.Query(ctx, getLabelsByTenantID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Label{}
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskLabels = `-- name: GetTaskLabels :many
SELECT l.id, l.name, l.color
FROM labels l
JOIN task_labels tl ON tl.label_id = l.id
WHERE tl.task_id = $1
ORDER BY l.name
`

type GetTaskLabelsRow struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	Color string      `json:"color"`
}

func (q *Queries) GetTaskLabels(ctx context.Context, taskID pgtype.UUID) ([]GetTaskLabelsRow, error) {
	rows, err := q.db.Query(ctx, getTaskLabels, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTaskLabelsRow{}
	for rows.Next() {
		var i GetTaskLabelsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskLabelsByBoardID = `-- name: GetTaskLabelsByBoardID :many
SELECT tl.task_id, l.id as label_id, l.name, l.color
FROM task_labels tl
JOIN labels l ON l.id = tl.label_id
JOIN tasks t ON t.id = tl.task_id
JOIN columns c ON c.id = t.column_id
WHERE c.board_id = $1 AND t.tenant_id = $2
`

type GetTaskLabelsByBoardIDParams struct {
	BoardID  pgtype.UUID `json:"board_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type GetTaskLabelsByBoardIDRow struct {
	TaskID  pgtype.UUID `json:"task_id"`
	LabelID pgtype.UUID `json:"label_id"`
	Name    string      `json:"name"`
	Color   string      `json:"color"`
}

func (q *Queries) GetTaskLabelsByBoardID(ctx context.Context, arg GetTaskLabelsByBoardIDParams) ([]GetTaskLabelsByBoardIDRow, error) {
	rows, err := q.db.Query(ctx, getTaskLabelsByBoardID, arg.BoardID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTaskLabelsByBoardIDRow{}
	for rows.Next() {
		var i GetTaskLabelsByBoardIDRow
		if err := rows.Scan(
			&i.TaskID,
			&i.LabelID,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTaskLabel = `-- name: RemoveTaskLabel :exec
DELETE FROM task_labels WHERE task_id = $1 AND label_id = $2
`

type RemoveTaskLabelParams struct {
	TaskID  pgtype.UUID `json:"task_id"`
	LabelID pgtype.UUID `json:"label_id"`
}

func (q *Queries) RemoveTaskLabel(ctx context.Context, arg RemoveTaskLabelParams) error {
	_, err := q.db.Exec(ctx, removeTaskLabel, arg.TaskID, arg.LabelID)
	return err
}
