// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (tenant_id, column_id, title, description, position, priority, assignee_id, due_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, column_id, title, description, position, assignee_id, due_date, created_at, updated_at, priority
`

type CreateTaskParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ColumnID    pgtype.UUID        `json:"column_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Position    int32              `json:"position"`
	Priority    string             `json:"priority"`
	AssigneeID  pgtype.UUID        `json:"assignee_id"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.TenantID,
		arg.ColumnID,
		arg.Title,
		arg.Description,
		arg.Position,
		arg.Priority,
		arg.AssigneeID,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.AssigneeID,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Priority,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1 AND tenant_id = $2
`

type DeleteTaskParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.TenantID)
	return err
}

const getMaxTaskPosition = `-- name: GetMaxTaskPosition :one
SELECT COALESCE(MAX(position), -1)::int as max_position
FROM tasks WHERE column_id = $1 AND tenant_id = $2
`

type GetMaxTaskPositionParams struct {
	ColumnID pgtype.UUID `json:"column_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetMaxTaskPosition(ctx context.Context, arg GetMaxTaskPositionParams) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxTaskPosition, arg.ColumnID, arg.TenantID)
	var max_position int32
	err := row.Scan(&max_position)
	return max_position, err
}

const getOverdueTasks = `-- name: GetOverdueTasks :many
SELECT t.id, t.title, t.priority, t.due_date,
       c.name as column_name,
       u.display_name as assignee_name
FROM tasks t
JOIN columns c ON c.id = t.column_id
LEFT JOIN users u ON u.id = t.assignee_id
WHERE t.tenant_id = $1 AND t.due_date < NOW()
ORDER BY t.due_date
`

type GetOverdueTasksRow struct {
	ID           pgtype.UUID        `json:"id"`
	Title        string             `json:"title"`
	Priority     string             `json:"priority"`
	DueDate      pgtype.Timestamptz `json:"due_date"`
	ColumnName   string             `json:"column_name"`
	AssigneeName pgtype.Text        `json:"assignee_name"`
}

func (q *Queries) GetOverdueTasks(ctx context.Context, tenantID pgtype.UUID) ([]GetOverdueTasksRow, error) {
	rows, err := q.db.Query(ctx, getOverdueTasks, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOverdueTasksRow{}
	for rows.Next() {
		var i GetOverdueTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Priority,
			&i.DueDate,
			&i.ColumnName,
			&i.AssigneeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT t.id, t.tenant_id, t.column_id, t.title, t.description,
       t.position, t.priority, t.assignee_id, t.due_date,
       t.created_at, t.updated_at,
       u.display_name as assignee_name, u.avatar_url as assignee_avatar
FROM tasks t
LEFT JOIN users u ON u.id = t.assignee_id
WHERE t.id = $1 AND t.tenant_id = $2
`

type GetTaskByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type GetTaskByIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	ColumnID       pgtype.UUID        `json:"column_id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Position       int32              `json:"position"`
	Priority       string             `json:"priority"`
	AssigneeID     pgtype.UUID        `json:"assignee_id"`
	DueDate        pgtype.Timestamptz `json:"due_date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AssigneeName   pgtype.Text        `json:"assignee_name"`
	AssigneeAvatar pgtype.Text        `json:"assignee_avatar"`
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (GetTaskByIDRow, error) {
	row := q.db.QueryRow(ctx, getTaskByID, arg.ID, arg.TenantID)
	var i GetTaskByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssigneeName,
		&i.AssigneeAvatar,
	)
	return i, err
}

const getTaskCountsByColumn = `-- name: GetTaskCountsByColumn :many
SELECT c.id as column_id, c.name as column_name,
       b.name as board_name, COUNT(t.id)::int as task_count
FROM columns c
JOIN boards b ON b.id = c.board_id
LEFT JOIN tasks t ON t.column_id = c.id
WHERE c.tenant_id = $1
GROUP BY c.id, c.name, b.name, c.position
ORDER BY b.name, c.position
`

type GetTaskCountsByColumnRow struct {
	ColumnID   pgtype.UUID `json:"column_id"`
	ColumnName string      `json:"column_name"`
	BoardName  string      `json:"board_name"`
	TaskCount  int32       `json:"task_count"`
}

func (q *Queries) GetTaskCountsByColumn(ctx context.Context, tenantID pgtype.UUID) ([]GetTaskCountsByColumnRow, error) {
	rows, err := q.db.Query(ctx, getTaskCountsByColumn, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTaskCountsByColumnRow{}
	for rows.Next() {
		var i GetTaskCountsByColumnRow
		if err := rows.Scan(
			&i.ColumnID,
			&i.ColumnName,
			&i.BoardName,
			&i.TaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByAssignee = `-- name: GetTasksByAssignee :many
SELECT t.id, t.title, t.priority, t.due_date,
       c.name as column_name, b.name as board_name
FROM tasks t
JOIN columns c ON c.id = t.column_id
JOIN boards b ON b.id = c.board_id
WHERE t.assignee_id = $1 AND t.tenant_id = $2
ORDER BY t.due_date NULLS LAST, t.created_at
`

type GetTasksByAssigneeParams struct {
	AssigneeID pgtype.UUID `json:"assignee_id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
}

type GetTasksByAssigneeRow struct {
	ID         pgtype.UUID        `json:"id"`
	Title      string             `json:"title"`
	Priority   string             `json:"priority"`
	DueDate    pgtype.Timestamptz `json:"due_date"`
	ColumnName string             `json:"column_name"`
	BoardName  string             `json:"board_name"`
}

func (q *Queries) GetTasksByAssignee(ctx context.Context, arg GetTasksByAssigneeParams) ([]GetTasksByAssigneeRow, error) {
	rows, err := q.db.Query(ctx, getTasksByAssignee, arg.AssigneeID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTasksByAssigneeRow{}
	for rows.Next() {
		var i GetTasksByAssigneeRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Priority,
			&i.DueDate,
			&i.ColumnName,
			&i.BoardName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByBoardID = `-- name: GetTasksByBoardID :many
SELECT t.id, t.column_id, t.title, t.position, t.priority,
       t.assignee_id, t.due_date,
       u.display_name as assignee_name, u.avatar_url as assignee_avatar
FROM tasks t
LEFT JOIN users u ON u.id = t.assignee_id
JOIN columns c ON c.id = t.column_id
WHERE c.board_id = $1 AND t.tenant_id = $2
ORDER BY t.column_id, t.position
`

type GetTasksByBoardIDParams struct {
	BoardID  pgtype.UUID `json:"board_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type GetTasksByBoardIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	ColumnID       pgtype.UUID        `json:"column_id"`
	Title          string             `json:"title"`
	Position       int32              `json:"position"`
	Priority       string             `json:"priority"`
	AssigneeID     pgtype.UUID        `json:"assignee_id"`
	DueDate        pgtype.Timestamptz `json:"due_date"`
	AssigneeName   pgtype.Text        `json:"assignee_name"`
	AssigneeAvatar pgtype.Text        `json:"assignee_avatar"`
}

func (q *Queries) GetTasksByBoardID(ctx context.Context, arg GetTasksByBoardIDParams) ([]GetTasksByBoardIDRow, error) {
	rows, err := q.db.Query(ctx, getTasksByBoardID, arg.BoardID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTasksByBoardIDRow{}
	for rows.Next() {
		var i GetTasksByBoardIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ColumnID,
			&i.Title,
			&i.Position,
			&i.Priority,
			&i.AssigneeID,
			&i.DueDate,
			&i.AssigneeName,
			&i.AssigneeAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByColumnID = `-- name: GetTasksByColumnID :many
SELECT id, tenant_id, column_id, title, description, position, assignee_id, due_date, created_at, updated_at, priority FROM tasks WHERE column_id = $1 AND tenant_id = $2 ORDER BY position
`

type GetTasksByColumnIDParams struct {
	ColumnID pgtype.UUID `json:"column_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetTasksByColumnID(ctx context.Context, arg GetTasksByColumnIDParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksByColumnID, arg.ColumnID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ColumnID,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.AssigneeID,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantTaskSummary = `-- name: GetTenantTaskSummary :one
SELECT
    COUNT(*)::int as total_tasks,
    COUNT(*) FILTER (WHERE t.due_date < NOW())::int as overdue_tasks
FROM tasks t WHERE t.tenant_id = $1
`

type GetTenantTaskSummaryRow struct {
	TotalTasks   int32 `json:"total_tasks"`
	OverdueTasks int32 `json:"overdue_tasks"`
}

func (q *Queries) GetTenantTaskSummary(ctx context.Context, tenantID pgtype.UUID) (GetTenantTaskSummaryRow, error) {
	row := q.db.QueryRow(ctx, getTenantTaskSummary, tenantID)
	var i GetTenantTaskSummaryRow
	err := row.Scan(&i.TotalTasks, &i.OverdueTasks)
	return i, err
}

const moveTask = `-- name: MoveTask :exec
UPDATE tasks SET column_id = $2, position = $3, updated_at = NOW()
WHERE id = $1 AND tenant_id = $4
`

type MoveTaskParams struct {
	ID       pgtype.UUID `json:"id"`
	ColumnID pgtype.UUID `json:"column_id"`
	Position int32       `json:"position"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) MoveTask(ctx context.Context, arg MoveTaskParams) error {
	_, err := q.db.Exec(ctx, moveTask,
		arg.ID,
		arg.ColumnID,
		arg.Position,
		arg.TenantID,
	)
	return err
}

const shiftTaskPositionsDown = `-- name: ShiftTaskPositionsDown :exec
UPDATE tasks SET position = position - 1, updated_at = NOW()
WHERE column_id = $1 AND tenant_id = $2 AND position > $3
`

type ShiftTaskPositionsDownParams struct {
	ColumnID pgtype.UUID `json:"column_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Position int32       `json:"position"`
}

func (q *Queries) ShiftTaskPositionsDown(ctx context.Context, arg ShiftTaskPositionsDownParams) error {
	_, err := q.db.Exec(ctx, shiftTaskPositionsDown, arg.ColumnID, arg.TenantID, arg.Position)
	return err
}

const shiftTaskPositionsUp = `-- name: ShiftTaskPositionsUp :exec
UPDATE tasks SET position = position + 1, updated_at = NOW()
WHERE column_id = $1 AND tenant_id = $2 AND position >= $3
`

type ShiftTaskPositionsUpParams struct {
	ColumnID pgtype.UUID `json:"column_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Position int32       `json:"position"`
}

func (q *Queries) ShiftTaskPositionsUp(ctx context.Context, arg ShiftTaskPositionsUpParams) error {
	_, err := q.db.Exec(ctx, shiftTaskPositionsUp, arg.ColumnID, arg.TenantID, arg.Position)
	return err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = COALESCE($1, title),
    description = COALESCE($2, description),
    priority = COALESCE($3, priority),
    assignee_id = COALESCE($4, assignee_id),
    due_date = COALESCE($5, due_date),
    updated_at = NOW()
WHERE id = $6 AND tenant_id = $7
RETURNING id, tenant_id, column_id, title, description, position, assignee_id, due_date, created_at, updated_at, priority
`

type UpdateTaskParams struct {
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	Priority    pgtype.Text        `json:"priority"`
	AssigneeID  pgtype.UUID        `json:"assignee_id"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.AssigneeID,
		arg.DueDate,
		arg.ID,
		arg.TenantID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.AssigneeID,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Priority,
	)
	return i, err
}
