// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, created_at, updated_at
`

type CreateTenantParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.Slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTenantMember = `-- name: CreateTenantMember :exec
INSERT INTO tenant_members (tenant_id, user_id, role)
VALUES ($1, $2, $3)
`

type CreateTenantMemberParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Role     string      `json:"role"`
}

func (q *Queries) CreateTenantMember(ctx context.Context, arg CreateTenantMemberParams) error {
	_, err := q.db.Exec(ctx, createTenantMember, arg.TenantID, arg.UserID, arg.Role)
	return err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, created_at, updated_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, created_at, updated_at FROM tenants WHERE slug = $1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantMemberByTenantAndUser = `-- name: GetTenantMemberByTenantAndUser :one
SELECT id, tenant_id, user_id, role, created_at FROM tenant_members WHERE tenant_id = $1 AND user_id = $2
`

type GetTenantMemberByTenantAndUserParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTenantMemberByTenantAndUser(ctx context.Context, arg GetTenantMemberByTenantAndUserParams) (TenantMember, error) {
	row := q.db.QueryRow(ctx, getTenantMemberByTenantAndUser, arg.TenantID, arg.UserID)
	var i TenantMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantMemberByUserID = `-- name: GetTenantMemberByUserID :one
SELECT id, tenant_id, user_id, role, created_at FROM tenant_members WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetTenantMemberByUserID(ctx context.Context, userID pgtype.UUID) (TenantMember, error) {
	row := q.db.QueryRow(ctx, getTenantMemberByUserID, userID)
	var i TenantMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantMembers = `-- name: GetTenantMembers :many
SELECT
    tm.user_id,
    u.email,
    u.display_name,
    u.avatar_url,
    tm.role,
    tm.created_at AS joined_at
FROM tenant_members tm
JOIN users u ON u.id = tm.user_id
WHERE tm.tenant_id = $1
ORDER BY tm.created_at
`

type GetTenantMembersRow struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) GetTenantMembers(ctx context.Context, tenantID pgtype.UUID) ([]GetTenantMembersRow, error) {
	rows, err := q.db.Query(ctx, getTenantMembers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTenantMembersRow{}
	for rows.Next() {
		var i GetTenantMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantsByUserID = `-- name: GetTenantsByUserID :many
SELECT t.id, t.name, t.slug, t.created_at, t.updated_at
FROM tenants t
JOIN tenant_members tm ON tm.tenant_id = t.id
WHERE tm.user_id = $1
ORDER BY t.created_at
`

func (q *Queries) GetTenantsByUserID(ctx context.Context, userID pgtype.UUID) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, getTenantsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTenantMember = `-- name: RemoveTenantMember :exec
DELETE FROM tenant_members WHERE tenant_id = $1 AND user_id = $2
`

type RemoveTenantMemberParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveTenantMember(ctx context.Context, arg RemoveTenantMemberParams) error {
	_, err := q.db.Exec(ctx, removeTenantMember, arg.TenantID, arg.UserID)
	return err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET name = COALESCE($1, name),
    slug = COALESCE($2, slug),
    updated_at = NOW()
WHERE id = $3
RETURNING id, name, slug, created_at, updated_at
`

type UpdateTenantParams struct {
	Name pgtype.Text `json:"name"`
	Slug pgtype.Text `json:"slug"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant, arg.Name, arg.Slug, arg.ID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantMemberRole = `-- name: UpdateTenantMemberRole :exec
UPDATE tenant_members SET role = $3
WHERE tenant_id = $1 AND user_id = $2
`

type UpdateTenantMemberRoleParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Role     string      `json:"role"`
}

func (q *Queries) UpdateTenantMemberRole(ctx context.Context, arg UpdateTenantMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateTenantMemberRole, arg.TenantID, arg.UserID, arg.Role)
	return err
}
